Issues #94 and #89 adding image sharing and image preview
muke1908/chat-e2ee pull request #108
Opened 2020-08-26 02:37 UTC by tskull01

2020-08-26 06:13 UTC, muke1908 requested changes

2020-08-26 06:13 UTC, muke1908 commented on client/src/utils/imagePicker.js
> +    }
```suggestion
    if (!file) {
        reject('No file selected')
    }
     reader.readAsDataURL(file);
```

2020-08-26 06:13 UTC, muke1908 commented on client/src/components/Messaging/Message.js
> +  const imgTest = body.match(regex);
```suggestion
  const isImg = body.match(regex);
```

2020-08-26 06:13 UTC, muke1908 commented on client/src/components/Messaging/Message.js
> +          {imgTest ? <Image src={body} maxWidth="100%" maxHeight="auto" /> : body}
```suggestion
          {isImg ? <Image src={body} maxWidth='300px' maxHeight='300px' /> : body}
```

2020-08-26 06:13 UTC, muke1908 commented on client/src/components/Messaging/NewMessageForm.js
> +              }
Let's create a separate function and call it here in `onChange`.

2020-08-26 06:13 UTC, muke1908 commented on client/src/pages/messaging/index.js
> +  const handleSubmit = (e, imgUrl = '') => {
It looks like design inconsistency. 
Either keep both text and imageUrl at the parent state or, pass both of them in the function argument.

2020-08-26 06:13 UTC, muke1908 commented on client/src/pages/messaging/index.js
> +    }
```suggestion
setMessages((prevMsg) =>
        prevMsg.concat({
          body: imgUrl || text,
          sender: userId,
          local: true
        })
      );
```

2020-08-26 06:15 UTC, muke1908 commented on client/src/components/Messaging/NewMessageForm.js
>        <div className={styles.imagePickerContainer}>
I would suggest making a separate component for imagePicker - which will pick and show preview

2020-08-26 09:00 UTC, muke1908 commented
Looks like you have deleted `.env.sample`

2020-08-27 15:57 UTC, tskull01 commented
It looks like PubNub errors on any message over 32 KB. From their forums they recommend either sending a URL that points to the image or sending the message in multiple parts. 

https://support.pubnub.com/support/solutions/articles/14000043783-can-i-send-large-messages-with-pubnub-

2020-08-27 17:35 UTC, muke1908 commented
> It looks like PubNub errors on any message over 32 KB. From their forums they recommend either sending a URL that points to the image or sending the message in multiple parts.
> 
> https://support.pubnub.com/support/solutions/articles/14000043783-can-i-send-large-messages-with-pubnub-

Hi @tskull01, yes we eventually have to upload the image separately with API. Let's merge this for now.
The idea of sharing image is https://github.com/muke1908/chat-e2ee/wiki/Idea:-Secure-image-sharing You can take a look

2020-08-27 17:37 UTC, merged