Audrey
muke1908/chat-e2ee pull request #133
Opened 2020-09-03 15:16 UTC by AudreyKj

Hello! I worked on the Button to retry fetching public key (issue 60: https://github.com/muke1908/chat-e2ee/issues/60)

-> button at the top allows to fetch key again on click 
-> button spins on loading and is not clickable 
-> button is not visible when key is received 

<img width="849" alt="Screen Shot 2020-09-03 at 17 15 07" src="https://user-images.githubusercontent.com/38159391/92133768-0ee18b00-ee09-11ea-9163-309aa73b2cf5.png">

2020-09-03 21:15 UTC, muke1908 requested changes

2020-09-03 21:15 UTC, muke1908 commented on client/src/components/Messaging/UserStatusInfo.js
> +  };
```suggestion
const fetchKeyAgain = async () => {
    if (loading) return;
    setLoading(true);
    await  getSetUsers(channelID);
    setLoading(false);
  };
```

2020-09-03 21:15 UTC, muke1908 commented on client/src/components/Messaging/UserStatusInfo.js
> +    setLoading(true);
this will keep loading = true forever if online doesn't change.

2020-09-04 06:33 UTC, AudreyKj commented
@muke1908 thanks for reviewing! I made the necessary changes: https://github.com/muke1908/chat-e2ee/compare/master...AudreyKj:audrey

2020-09-04 06:48 UTC, merged