Added image picker and emoji picker dark icons for light theme
muke1908/chat-e2ee pull request #156
Opened 2020-10-01 06:23 UTC by manny525

The image picker and emoji picker icons where not visible in the light theme.

2020-10-01 07:02 UTC, muke1908 requested changes

2020-10-01 07:02 UTC, muke1908 commented on client/src/components/Messaging/ImagePicker/index.js
> +import { ThemeContext } from '../../ThemeContext.js';
The build is failing here.

2020-10-01 07:03 UTC, muke1908 commented
@all-contributors, please add @manny525 for code.

2020-10-01 07:05 UTC, muke1908 commented
@all-contributors please add @manny525 for code.

2020-10-01 07:51 UTC, merged

2020-10-07 10:17 UTC, manny525 commented
@muke1908 do you mind adding the hacktoberfest-accepted label to this PR?