Chat link deletion button added.
muke1908/chat-e2ee pull request #162
Opened 2020-10-01 12:22 UTC by manny525

2020-10-01 15:51 UTC, Narasimha1997 commented
Can anyone delete the chatlink? If they have the chatlink`uuid` ??

2020-10-01 17:04 UTC, muke1908 commented
@Narasimha1997 you are correct but the chances of guessing right UUIDs are extremely small, it's not worth serious consideration. If you think carefully, chances of your password being rightly guessed are much higher.

Still, there are a few vulnerabilities in terms of DDoS, and it can be prevented by adding the rate limiter. 

I added "delete" feature keeping the following things in mind:
1. Chat link is meant for **only** receiver / sender.
2. Both receiver / sender will have the right to invalidate the chat link at any point in time.

Yes, if chat link is compromised there can be security issues but that is obvious, isn't it?
Even if I assume the chat link is compromised, then the only next best option for the user is to be able to invalidate the link so that other people can't impersonate. 

In terms of vulnerability, the attacker can only delete a link.

2020-10-01 17:44 UTC, Narasimha1997 commented
@muke1908 , Yes you are right. Of coure UUID can't be guessed, I didn't mean it can be guessed. 
 The delete api takes chatlink UUID directly to delete the record. The one who possess chatlink can do anything according to the current architecture, they can join the chat as well as delete it. 

The API returns Chatlink to the frontend according to issue #159. One suggestion would be to avoid sending chatlink to frontend or avoid sending chatlink in clear text (you can encrypt it with the PIN)

One more suggestion: Can we keep PIN validation for delete api? So that it would be like a double check, if someone steals the chatlink, they still need PIN to delete the chatlink.

2020-10-01 18:25 UTC, muke1908 commented
>The API returns Chatlink to the frontend according to issue #159. One suggestion would be to avoid sending chatlink to frontend or avoid sending chatlink in clear text (or you can just send the hash of chatlink), in other words avoid frontend from knowing the actual chatlink.

But anyway we'll have to redirect them to the chat link frontend needs to know the link.

>One more suggestion: Can we keep PIN validation for delete api? So that it would be like a double check, if someone steals the chatlink, they still need PIN to delete the chatlink.

Yes, this can add an extra layer of security but, the user will have to memorize the PIN. But I somewhat feel, unnecessary.

2020-10-03 12:36 UTC, manny525 commented
Do let me know what changes are required and I'll try to get them done

2020-10-03 15:52 UTC, muke1908 commented
> Do let me know what changes are required and I'll try to get them done

Hi, I didn't get time to review the PR completely. As I understood, you are showing the delete button only when the link is active, but the user should be able to delete the link at any point of time. 

Also, please resolve the merge conflicts.

2020-10-05 10:12 UTC, muke1908 requested changes

2020-10-05 10:12 UTC, muke1908 commented on .env.sample
> +GOOGLE_RECAPTCHA_SECRET=''
```suggestion
```

2020-10-05 10:12 UTC, muke1908 commented on client/src/components/Messaging/LinkSharingInstruction/index.js
> +  };
Let's show some loading state, then redirect to homepage.

2020-10-05 10:12 UTC, muke1908 commented on client/src/components/Messaging/LinkSharingInstruction/index.js
> +      </div>
Please move it outside. 'Delete link' is not really related with `LinkSharingInstruction` component. Also, we need to display the delete button always. Let's add the button to the top right corner - next to theme toggle button.

2020-10-05 10:12 UTC, muke1908 commented on client/src/service/deleteLink.js
> +const getLink = async ({ channelID }) => {
`deleteLink`

2020-10-06 07:19 UTC, muke1908 commented
@manny525 Hi, I have left a few comments. Please check.

2020-10-07 08:21 UTC, manny525 commented
On it @muke1908

2020-10-07 09:59 UTC, muke1908 commented
Hi @manny525, the build is failing in your last commit. Can you please fix this?

2020-10-07 10:26 UTC, merged