feat: add PIN Support
muke1908/chat-e2ee pull request #169
Opened 2020-10-07 00:51 UTC by pavan5555

- Added PIN support 

- Displays PIN along with the Link generation.
- Displays the PIN Valid for 30 minutes msg

![image](https://user-images.githubusercontent.com/48689971/95275082-29928f80-080d-11eb-978b-96f2bc5a8e62.png)

2020-10-07 06:05 UTC, muke1908 requested changes

2020-10-07 06:05 UTC, muke1908 commented on client/src/components/LinkDisplay/index.js
> +import PinDisplay from './../PinDisplay/index.js';
```suggestion
import PinDisplay from './../PinDisplay';
```

2020-10-07 06:07 UTC, muke1908 commented
@pavan5555 thanks for the PR, wondering if you add the same to the chat page as well? 
<img width="829" alt="Screen Shot 2020-10-07 at 9 06 56 AM" src="https://user-images.githubusercontent.com/20297989/95293626-79f50600-087c-11eb-8065-c9f1823f00c4.png">

2020-10-07 06:13 UTC, pavan5555 commented
Yes!, will you create a new issue ? or I use the same issue ?, so sorry about these questions.

2020-10-07 06:14 UTC, muke1908 commented
> Yes!, will you create a new issue ? or I use the same issue ?, so sorry about these questions.

Let's do it in the scope of this issue.

2020-10-07 06:17 UTC, pavan5555 commented
> > Yes!, will you create a new issue ? or I use the same issue ?, so sorry about these questions.
> 
> Let's do it in the scope of this issue.

Sure!

2020-10-08 00:11 UTC, pavan5555 commented
Hello @muke1908  I have pushed the changes

- Added PIN Display in chat page 
- Worked on the CSS issue in the chat page in light mode.

![image](https://user-images.githubusercontent.com/48689971/95400717-ee599480-08d0-11eb-8c83-bdc89dc6fb49.png)

2020-10-08 06:57 UTC, muke1908 requested changes
Please resolve the conflicts.

2020-10-08 06:57 UTC, muke1908 commented on client/src/components/LinkDisplay/index.js
> +          href={`${content.absoluteLink}?pin=${content.pin}`}
Adding PIN in url parameter - it's a security vulnerability. 
Please add a **To Do** comment that "this needs to be changed - make an POST endpoint to fetch the PIN of an url"

2020-10-08 19:29 UTC, merged