Lock Button
muke1908/chat-e2ee pull request #183
Opened 2020-12-18 02:24 UTC by ZackKuptsow

Lock button toggle that changes url. 
Content includes locked option now. 
Adds pin to url if locked equals true.

2020-12-18 07:53 UTC, muke1908 commented
Hi @ZackKuptsow, thank you for the PR. Can you please fix the build, it's failing?
```
./src/pages/messaging/helpers/index.js
  Line 31:9:  'lockedStatus_storage' is assigned a value but never used  no-unused-vars

./src/components/LockToggle/index.js
  Line 6:10:   'LockContext' is defined but never used        no-unused-vars
  Line 19:10:  'darkMode' is assigned a value but never used  no-unused-vars
  Line 31:20:  Expected '===' and instead saw '=='            eqeqeq

./src/index.js
  Line 9:50:  'Link' is defined but never used      no-unused-vars
  Line 9:56:  'Redirect' is defined but never used  no-unused-vars
  ```

2020-12-18 18:39 UTC, ZackKuptsow commented
@muke1908 removed the unnecessary code and files to pass the build test

2020-12-19 18:35 UTC, muke1908 requested changes
As I understood you tried to work on issue #170. 
As this PR is partial implementation, I would like to merge it keeping the origin issue open. 
Please look at my comments.

2020-12-19 18:35 UTC, muke1908 commented on client/package.json
> +    "website-scraper": "^4.2.3"
looks like `website-scraper` and `bluebird` are unnecessary and never used

2020-12-19 18:35 UTC, muke1908 commented on client/src/LockContext.js
> +defaultLockMode = defaultLockMode === null ? false : defaultLockMode;
```suggestion
const defaultLockMode = !!storage.get('locked');
```

2020-12-19 18:35 UTC, muke1908 commented on client/src/components/LinkDisplay/index.js
> +          href={`${content.absoluteLink}?pin=${content.pin}&?locked=${content.locked}`}
Why do you need to pass `locked` in link?

2020-12-19 18:35 UTC, muke1908 commented on client/src/pages/chatlink/captcha.js
> +};
This file is not used anywhere

2020-12-19 18:35 UTC, muke1908 commented on client/src/components/LockToggle/index.js
> +  };
```suggestion
const toggleLock = () => {
    storage.set('locked', !lockMode);
    setLockMode(!lockMode);
}
```
This implementation needs to go to the backend. For now, let's leave it as suggested.

2021-06-12 18:38 UTC, closed without merging