added param in setchannel and stored in ChatE2EE class
muke1908/chat-e2ee pull request #327
Opened 2023-07-27 19:32 UTC by karandeep4423

added param in setchannel and stored in ChatE2EE class

2023-07-28 07:16 UTC, muke1908 requested changes

2023-07-28 07:16 UTC, muke1908 commented on service/src/public/types.ts
> +    setChannel(channelId: string, userId: string, userName: string): void;
can you make it optional? `username?: string`

2023-07-28 07:16 UTC, muke1908 commented on service/src/sdk.ts
> +    public async setChannel(channelId: string, userId: string, userName: string): Promise<void> {
same here, please make username optional.

2023-07-30 12:28 UTC, karandeep4423 commented
i have added optional params

2023-07-31 08:41 UTC, merged