added feature of terminating when the link is deleted issue number #352 issue has been solved
muke1908/chat-e2ee pull request #375
Opened 2024-09-13 12:40 UTC by chandankumarm55

Hey, thanks for assigning this issue to me!

I successfully implemented this feature. Most of the files show changes due to the addition of a cursor at the end. In the frontend, we used a useEffect hook to validate whether the link is valid or not. We also applied a throttling concept to check this condition every second. You can modify the interval to your preference, but 1 second is optimal for performance. 

Things you need to change for production mode:

You need to update the URL used for sending the request in the file client/src/pages/messaging/index.tsx at line 270. For production, the URL should be https://chat-e2ee-2.azurewebsites.net/api/chat-link/status/${channelID}. Make sure you use backticks for this. For now, I’ve used localhost for running it locally.

![Screenshot 2024-09-13 125631](https://github.com/user-attachments/assets/1edc7813-aa61-4431-b2c5-d4e948ebca7d)

Please refer to the commits for a better understanding. You can also use an .env file and access the URL via process.env.BACKEND_URL, but for now, I’ve added the URL directly to reduce confusion.

I have also tested the app locally. Only one test failed due to the absence of an absolute link, which we declared as undefined. This is causing the following error:

The detailed failed test case can be found in the file backend/api/chatLink/utils/link.test.ts at line 19. The error is caused by absoluteLink: undefined, which is why the test failed.

![Screenshot 2024-09-13 130357](https://github.com/user-attachments/assets/01e73508-d58b-426c-a65e-4db755bd238b)

![Screenshot 2024-09-13 130424](https://github.com/user-attachments/assets/4ff0395d-9c53-441e-b7aa-9d26e7d8b5c7)

i think this is not matter that much . and console when we start the app looks like 

![Screenshot 2024-09-13 134939](https://github.com/user-attachments/assets/94932311-0b52-40f4-b0ec-d5e7ac9b2f43)

I implemented the feature where the throttling function runs every second and renders the component when linkActive becomes invalid. After 2 seconds, it will navigate to the / route (home route). You can adjust this timing based on your preference.

I chose 2 seconds as an optimal delay to inform the user that the link is invalid. Using a longer delay might send more requests to the backend, leading to performance issues. On the other hand, if we use a 1-second delay, there might not be enough time for the user to read the message. Therefore, I think 2 seconds strikes a good balance, but you can modify it according to your needs.

https://github.com/user-attachments/assets/ed78425e-e80e-48df-b468-f195c0c07c7d

now Related to delete link feature #352 issue has been solved 

fell free to as anything , to ask regarding this issue impentation . Thank you for guiding at every step @muke1908

2024-09-13 12:46 UTC, chandankumarm55 commented
@muke1908  i have installed many libraries i faced difficulty in running the application at starting so it showing there is conflicts in package.json you can omit or remove those unwanted later please merge it as soon as possible .

2024-09-13 13:16 UTC, muke1908 requested changes

2024-09-13 13:16 UTC, muke1908 commented on backend/api/chatLink/utils/link.ts
> +const CHAT_LINK_DOMAIN = process.env.CHAT_LINK_DOMAIN || 'http://localhost:3000';
Please remove this fallback.

2024-09-13 13:16 UTC, muke1908 commented on backend/db/index.ts
> +const dbName = process.env.MONGO_DB_NAME || 'realtimechatting';
Please remove the arbitrary defaults. Let it be set explicitly in .env

2024-09-13 13:16 UTC, muke1908 commented on backend/db/index.ts
> +console.log('uri', uri);
unnecessary `console.log`

2024-09-13 13:16 UTC, muke1908 commented on client/src/pages/messaging/index.tsx
> +function throttle<T extends (...args: any[]) => void>(func: T, limit: number): (...args: Parameters<T>) => void {
can be moved to ./utils.

2024-09-13 13:16 UTC, muke1908 commented on client/src/pages/messaging/index.tsx
> +      const URL = `http://localhost:3001/api/chat-link/status/${channelID}`
urls should not be hard-coded. Also UI layer  does not need to know anything about the server. That's why we have the service. 
You can expose another method in `service`, and use that here.

2024-09-13 14:20 UTC, chandankumarm55 commented
@muke1908  can please guide me what and all need to make change in order to create new method ?

2024-09-13 14:22 UTC, muke1908 commented
> @muke1908 can please guide me what and all need to make change in order to create new method ?

I think you already did it earlier here https://github.com/muke1908/chat-e2ee/issues/352#issuecomment-2336803634

2024-09-13 14:31 UTC, chandankumarm55 commented
yes i did but  the error not found so first i created method in sdk.ts and added that in types.ts after that  run build command then also it didnt reflect on my frontend

2024-09-13 14:34 UTC, muke1908 commented
> yes i did but the error not found so first i created method in sdk.ts and added that in types.ts after that run build command then also it didnt reflect on my frontend

Did you try this https://github.com/muke1908/chat-e2ee/issues/352#issuecomment-2345574879

2024-09-13 16:20 UTC, chandankumarm55 commented
@muke1908  after trying only i purposed this method . i tried for more then 2 days but  it showing same error method is not found . please mention a detailed description how to create new method in service folder and how backend folder interact with service folder please

2024-09-13 16:42 UTC, muke1908 commented
> @muke1908 after trying only i purposed this method . i tried for more then 2 days but it showing same error method is not found . please mention a detailed description how to create new method in service folder and how backend folder interact with service folder please


1. go to `./service`, run `npm link`
2. go to `./client`, delete `node_modules`, run `npm link @chat-e2ee/service`, run `npm install`

Once it's done, if you make change in `./service` and run build it will immediately reflect in `./client`

2024-10-16 12:48 UTC, closed without merging

2024-10-16 12:48 UTC, muke1908 commented
closing as redundant